//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Lt_GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_Lt_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rt_GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_Rt_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Lt_GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_Lt_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rt_GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_Rt_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean Lt_Trackpad
        {
            get
            {
                return SteamVR_Actions.default_Lt_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rt_Trackpad
        {
            get
            {
                return SteamVR_Actions.default_Rt_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Lt_TrackpadPos
        {
            get
            {
                return SteamVR_Actions.default_Lt_TrackpadPos;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rt_TrackpadPos
        {
            get
            {
                return SteamVR_Actions.default_Rt_TrackpadPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean Lt_Menu
        {
            get
            {
                return SteamVR_Actions.default_Lt_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rt_Menu
        {
            get
            {
                return SteamVR_Actions.default_Rt_Menu;
            }
        }
        
        public virtual SteamVR_Action_Pose Lt_pose
        {
            get
            {
                return SteamVR_Actions.default_Lt_pose;
            }
        }
        
        public virtual SteamVR_Action_Pose Rt_pose
        {
            get
            {
                return SteamVR_Actions.default_Rt_pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
